S02 us20 créer table especes
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #107
Opened 2022-11-07 15:44 UTC by Planger45

2022-11-07 19:53 UTC, DrissB45 approved these changes

2022-11-08 08:00 UTC, sblondeau requested changes
créer une table ce n'est par une US (pas une fonctionnalité, tu vas pas dire en tant que XXX je veux créer une table dans la bdd...) , c'est par ex une tache de la US "En tant que visiteur, je veux lister les espèces d'un circuit, afin de pouvoir les identifier quand je me promène"

2022-11-08 16:08 UTC, cedriclv approved these changes

2022-11-08 22:02 UTC, DrissB45 commented on src/Controller/RaceController.php
> +        if (!isset($race['picture']) || empty($race['picture'])) {
tu gères l'upload de l'image dans ton add() ?

2022-11-08 22:31 UTC, Planger45 commented on src/Controller/RaceController.php
> +        $race = [];
Attention, l'assignation n'est pas le même sens dans ce cas de figure, j'initialise la variable $race et $errors en tableau, si je suis ton raisonnement cela voudrait dire que ma variable $race contient le tableau $errors :)

2022-11-08 22:38 UTC, Planger45 commented on src/Controller/RaceController.php
> +        if (!isset($race['name']) || empty($race['name'])) {
Les deux n'ont pas la même signification, l'un test si elle est "vide" et l'autre si elle est déclaré. Et le sens est surement inversé d'ailleurs :)

2022-11-08 22:39 UTC, Planger45 commented on src/Controller/RaceController.php
> +        if (!isset($race['picture']) || empty($race['picture'])) {
Nop j'envoi via un lien url la photo

2022-11-08 22:39 UTC, Planger45 commented on public/assets/css/form.css
> +.list-errors {
J'ai fais les modifs

2022-11-08 22:39 UTC, Planger45 commented on database.sql
> +    `race` (
Okay je change tout :P

2022-11-08 23:14 UTC, Planger45 commented
Ajout de la table et de l'index Species

2022-11-09 16:13 UTC, DrissB45 approved these changes

2022-11-09 16:13 UTC, DrissB45 commented on database.sql
> +        `picture` TEXT NOT NULL
varchar

2022-11-09 22:27 UTC, sblondeau commented on src/View/Species/index.html.twig
> +					<button class="btn btn-secondary">
soit c'est button class="btn" si tu es dans un form
soit c'est a class="btn" si tu veux un lien avec une apparence de button
mais jamais un a dans un button !!

2022-11-12 11:06 UTC, DrissB45 commented on src/View/Organism/index.html.twig
> +										<button type="submit" class="btn btn-danger">Supprimer</button>
Pas besoin d'ajouter un type à un button : soit un button sans type, soit un input type submit

2022-11-14 08:29 UTC, sblondeau requested changes

2022-11-14 08:29 UTC, sblondeau commented on src/Controller/OrganismController.php
> +        $organisms = $organismManager->selectAll();
selectAll('name')  => pour trier par nom, plus simple pour s'y retrouver

2022-11-14 08:29 UTC, sblondeau commented on src/View/Organism/index.html.twig
> +										<a class="btn btn-primary" href="/especes/editer">Editer</a>
Éditer (accent majuscule)

2022-11-14 09:30 UTC, DrissB45 approved these changes

2022-11-14 10:24 UTC, sblondeau approved these changes

2022-11-14 10:24 UTC, merged