S02 us28 update activity
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #108
Opened 2022-11-07 18:34 UTC by cedriclv

2022-11-07 19:58 UTC, DrissB45 approved these changes
RAS au niveau du code pour ma part.

2022-11-07 19:58 UTC, DrissB45 commented on src/Controller/ActivityController.php
> +                    $errors[] = 'L\'image doit etre avoir une taille maxi de ' . self::MAX_PICTURE_SIZE / 1000 . ' Ko';
L'image doit avoir*

2022-11-08 09:57 UTC, sblondeau requested changes
tu as show et edit dans la meme PR
d'ailleurs as tu vraiment besoin d'un show coté admin ? ou alors c'est un show coté visiteur ? mais tu devrais alors avoir 2 controlleurs, un ActivityController pour l'index() et le show() coté visiteur, et un AdminActivityController pour l'admin des activités, ça sera mieux découpé

2022-11-08 09:57 UTC, sblondeau commented on src/Controller/ActivityController.php
> +                    $errors[] = 'L\'image doit etre avoir une taille maxi de ' . self::MAX_PICTURE_SIZE / 1000 . ' Ko';
pas corrigé

2022-11-08 09:57 UTC, sblondeau commented on src/Controller/ActivityController.php
> +                    $errors[] = 'L\'image doit etre de type ' . implode(", ", $allowedExtension);
être (accent) => manque à plein d'endroit

2022-11-08 09:57 UTC, sblondeau commented on src/View/Activity/edit.html.twig
> +    <legend class="row">AJOUT ADMIN</legend>
meme retorur que sur l'autre PR sur le fieldset

2022-11-10 10:04 UTC, closed without merging