S02 us16
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #109
Opened 2022-11-08 16:08 UTC by DrissB45

2022-11-09 00:21 UTC, Planger45 commented on src/View/Circuits/circuits-add.html.twig
> +	<!doctype html>
tu n'as pas besoin de ça vu que l'on a le layout admin avec tout dedans :)

2022-11-09 00:21 UTC, Planger45 commented on src/View/layout-admin.html.twig
> +<!doctype html>
On a déjà un layout Admin via la PR de Cédric tu peux supprimer celui-ci (désolé :S)

2022-11-09 00:21 UTC, Planger45 commented on src/routes.php
> +    'admin/circuits' => ['CircuitController', 'addCircuit']
Il faudra que l'on détermine un chemin identique pour tout le monde. A décider avec cédric pour que l'on ai pas 4 façons différentes de l'écrire :) (j'aime bien ta version)

2022-11-09 13:33 UTC, Planger45 submitted a review, later dismissed

2022-11-09 14:09 UTC, Planger45 approved these changes

2022-11-09 14:21 UTC, sblondeau requested changes

2022-11-09 14:21 UTC, sblondeau commented on src/Controller/CircuitController.php
> +            $circuit = array_map('htmlentities', $circuit);
non pas de htmlentities avant l'insertion en bdd
uniquement à l'affichage et Twig le gère déjà par défaut

2022-11-09 14:21 UTC, sblondeau commented on src/Controller/CircuitController.php
> +            $uploadDir = "./assets/upload/";
pas besoin du point avant le slash normaleemnt

2022-11-09 14:21 UTC, sblondeau commented on src/Controller/CircuitController.php
> +            $errors = $this->validateA($circuit, $errors);
trouve moi un meilleur nommage
validateEmpty()
validateSize(), etc. mais pas A et B

2022-11-09 14:21 UTC, sblondeau commented on src/View/Circuits/chooseCircuits.html.twig
> +										<img src="/../assets/upload/{{circuit.picture}}" class="card-img img-responsive" alt="image_circuits">
normalement /assets/upload ça fonction, pas de /../ devant :pensive:

2022-11-09 14:21 UTC, sblondeau commented on database.sql
> +        `picture` TEXT
un VARCHAR suffit

2022-11-09 14:21 UTC, sblondeau commented on src/View/Circuits/circuits-add.html.twig
> +						<form class="container" method="post" enctype="multipart/form-data">
quand tu as un type varchar en BDD => input type text
quand tu as un type TEXT en BDD => textarea

2022-11-09 14:21 UTC, sblondeau commented on src/View/Circuits/circuits-add.html.twig
> +								<input type="text" class="form-control" name="size" id="size" placeholder="7.0" value="{{circuit.size ?? '' }}" required>
type number ?

2022-11-11 17:32 UTC, cedriclv commented on src/View/Circuits/circuits-add.html.twig
> +						<form class="container" method="post" enctype="multipart/form-data">
pas sur de voir un changement fait la dessus. Comme je ne sais pas si vous avez convenu autrement je valide pour ne pas bloquer

2022-11-11 17:32 UTC, cedriclv commented on src/View/Circuits/circuits-add.html.twig
> +								<input type="text" class="form-control" name="size" id="size" placeholder="7.0" value="{{circuit.size ?? '' }}" required>
pas sur de voir un changement fait la dessus. Comme je ne sais pas si vous avez convenu autrement je valide pour ne pas bloquer

2022-11-11 17:33 UTC, cedriclv submitted a review, later dismissed
il y a les deux derniers points que je n'ai pas vu mis à jour, je valide quand meme, etant absent, je ne sais pas si vous l'avez dsicuté de vive voix. Tout le reste me sembl ok.

2022-11-14 08:58 UTC, sblondeau requested changes

2022-11-14 08:58 UTC, sblondeau commented on src/Controller/CircuitController.php
> +                $errors[] = 'Veuillez sélectionner une image de type .jpg, .jpeg, .png ou .webp !';
fais plus qq chose comme ça pour avoir un message d'erreur plus dynamique
 $errors[] = 'Veuillez sélectionner une image de type ' . implode(', ', $authorizedExtensions);

2022-11-14 08:58 UTC, sblondeau commented on src/Controller/CircuitController.php
> +                $circuitManager->save(
pourquoi ne pas faire tt simplement save($circuit, $uploadFinalName);

2022-11-14 08:58 UTC, sblondeau commented on src/Controller/CircuitController.php
> +        if (empty($circuit['size'])) {
2 fois  la meme verif sur size ?

2022-11-14 08:58 UTC, sblondeau commented on src/Controller/CircuitController.php
> +        if (!filter_var($circuit['size'], FILTER_VALIDATE_FLOAT)) {
+ verif que c'est un positif

2022-11-14 10:25 UTC, sblondeau approved these changes

2022-11-14 10:26 UTC, merged