first commit for the fix to put again the files who disappeared
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #111
Opened 2022-11-09 08:10 UTC by cedriclv

2022-11-09 14:13 UTC, Planger45 submitted a review, later dismissed

2022-11-09 14:24 UTC, sblondeau requested changes
reprendre tous les textes d'erreurs et corriger les fautes (accents notamment)

2022-11-09 14:24 UTC, sblondeau commented on src/Controller/ActivityController.php
> +            $errors[] = 'La description doit être complété';
complétée

2022-11-09 14:24 UTC, sblondeau commented on src/Controller/ActivityController.php
> +            $errors[] = 'La description ne doit pas faire plus de ' . self::MAX_LENGTH_DESCRIPTION . ' caracteres';
caractères (accent)

2022-11-09 14:24 UTC, sblondeau commented on src/Controller/ActivityController.php
> +            $errors[] = 'Le titre ne doit pas faire plus de ' . self::MAX_LENGTH_TITLE . ' caracteres';
caractères (accent)

2022-11-09 14:24 UTC, sblondeau commented on src/Controller/ActivityController.php
> +                $errors[] = 'L\'image doit etre avoir une taille maximum de ' . self::MAX_PICTURE_SIZE / 1000 . ' Ko';
accent, syntaxe...

2022-11-09 14:24 UTC, sblondeau commented on src/View/Activity/add.html.twig
> +    <legend class="row">AJOUT ADMIN</legend>
tjs fieldset et legent qui sont inutiles

2022-11-09 14:24 UTC, sblondeau commented on src/View/Activity/add.html.twig
> +  <li>{{error}}</li>
erreurs au dessus du form => j'ai l'impression d'avoir déjà fait ces retours plusieurs fois...

2022-11-09 16:15 UTC, DrissB45 approved these changes

2022-11-10 08:20 UTC, Zakari-B approved these changes

2022-11-10 08:20 UTC, merged