Fix activity dev
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #116
Opened 2022-11-09 22:45 UTC by Planger45

2022-11-09 22:45 UTC, Planger45 commented
Remise en place du responsive et des cards img :)

2022-11-09 22:54 UTC, DrissB45 commented on src/View/Activity/activity.html.twig
> +							<div class="col-12 col-lg-5 m-auto">
col-12 pas nécessaire car comportement par défaut de bootstrap

2022-11-09 22:57 UTC, Planger45 commented on src/View/Activity/activity.html.twig
> +							<div class="col-12 col-lg-5 m-auto">
Ouais j'ai vu le com de Sylvain faudra que je les dégage tous j'en ai mis partout :P

2022-11-10 08:51 UTC, Zakari-B submitted a review, later dismissed

2022-11-10 09:41 UTC, sblondeau requested changes

2022-11-10 09:41 UTC, sblondeau commented on src/View/Activity/activity.html.twig
> +				{% else %}
il ne faut pas tout répéter en odd et en even, juste modifier un order 
en css ou en bootstrap direct https://getbootstrap.com/docs/5.2/utilities/flex/#order

2022-11-10 09:41 UTC, sblondeau commented on src/View/Activity/activity.html.twig
> +				{% if loop.index is even %}
il ne faut pas tout répéter en odd et en even, juste modifier un order 
en css ou en bootstrap direct https://getbootstrap.com/docs/5.2/utilities/flex/#order

2022-11-10 10:37 UTC, DrissB45 approved these changes

2022-11-10 10:45 UTC, Zakari-B approved these changes

2022-11-10 10:45 UTC, merged