first commit for this US/ update fonction without show function
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #120
Opened 2022-11-10 10:00 UTC by cedriclv

ceci remplace cette US trop globale:
 S02 us28 update activity #108

2022-11-10 10:20 UTC, DrissB45 commented on src/Controller/ActivityController.php
> +                $targetDir = "./assets/upload/";
enlève le point et le slash
"assets/upload"

2022-11-10 10:20 UTC, DrissB45 commented on src/Controller/ActivityController.php
> +                $allowedExtension = ['jpg','png'];
on ajoute 'jpeg' et 'webp' en extensions autorisées

2022-11-10 10:20 UTC, DrissB45 commented on src/Controller/ActivityController.php
> +                    $errors[] = 'L\'image doit avoir une taille maxi de ' . self::MAX_PICTURE_SIZE / 1000 . ' Ko';
maximale*

2022-11-10 10:20 UTC, DrissB45 commented on src/Controller/ActivityController.php
> +                    $errors[] = 'L\'image doit avoir une taille maxi de ' . self::MAX_PICTURE_SIZE / 1000 . ' Ko';
On demande aussi une taille maximale de 1 Mo désormais

2022-11-10 10:48 UTC, cedriclv commented on src/Controller/ActivityController.php
> +                    $errors[] = 'L\'image doit avoir une taille maxi de ' . self::MAX_PICTURE_SIZE / 1000 . ' Ko';
Merci pour les checks Driss ;-)

2022-11-10 10:51 UTC, cedriclv commented on src/Controller/ActivityController.php
> +                $targetDir = "./assets/upload/";
done

2022-11-10 10:51 UTC, cedriclv commented on src/Controller/ActivityController.php
> +                $allowedExtension = ['jpg','png'];
done

2022-11-10 10:57 UTC, DrissB45 submitted a review, later dismissed

2022-11-10 16:19 UTC, sblondeau requested changes

2022-11-10 16:19 UTC, sblondeau commented on src/Model/ActivityManager.php
> +        $query1 = " SET `title` = :title, `description` = :description, `picture` = :picture WHERE id=:id";
tu es sur d'avoir besoin de faire une condition pour picture s'il est nulalble ? passe une  chaine vide au pire si tu as pas d'image, comme ça pas la peine de faire ta condition

2022-11-11 17:18 UTC, cedriclv commented on src/Model/ActivityManager.php
> +        $query1 = " SET `title` = :title, `description` = :description, `picture` = :picture WHERE id=:id";
ok merci, je viens de le changer.

2022-11-12 11:09 UTC, DrissB45 commented on src/View/Activity/edit.html.twig
> +    <button class="btn btn-primary">Mettre à jour</input>
< /button > au lieu de < /input > à la fin

2022-11-12 13:10 UTC, DrissB45 requested changes

2022-11-12 13:10 UTC, DrissB45 commented on src/View/Activity/edit.html.twig
> +    </div class="mb-3">
attention, tu as dû oublier qqch ici
Ferme la < /div> et réouvre une autre < /div > après où tu mets class="mb-3"

2022-11-12 14:10 UTC, Planger45 requested changes

2022-11-12 14:10 UTC, Planger45 commented on src/View/Activity/edit.html.twig
> +{% block content %}
Il faudra ajouter le block twig title pour les vues :)

2022-11-13 09:33 UTC, cedriclv commented on src/View/Activity/edit.html.twig
> +    <button class="btn btn-primary">Mettre à jour</input>
done

2022-11-13 09:34 UTC, cedriclv commented on src/View/Activity/edit.html.twig
> +    </div class="mb-3">
done

2022-11-13 09:44 UTC, cedriclv commented on src/View/Activity/edit.html.twig
> +{% block content %}
done

2022-11-14 08:52 UTC, DrissB45 submitted a review, later dismissed

2022-11-14 10:30 UTC, sblondeau requested changes

2022-11-14 10:30 UTC, sblondeau commented on src/Controller/ActivityController.php
> +                if ($_FILES['picture']['name'] > 0) {
if ($_FILES['picture']['name'] > 0) {
pas plutot 'errors' au lieu de 'name' ?
pourquoi ne pas le mettre au dessus avec la gestion des autres errors ?

2022-11-14 10:30 UTC, sblondeau commented on src/Controller/ActivityController.php
> +                    $activityManager->update($activity);
pas certain de ce else ?
si tu as un pb d'upload, veux tu tout de meme update les autres infos ?

2022-11-14 11:10 UTC, cedriclv commented on src/Controller/ActivityController.php
> +                if ($_FILES['picture']['name'] > 0) {
non en fait, c'est pour verifier qu'une image est bien la (donc avec une taille supererieure à 0), je viens donc de remplacer par:
                if ($_FILES['picture']['size'] > 0) {

2022-11-14 11:14 UTC, cedriclv commented on src/Controller/ActivityController.php
> +                    $activityManager->update($activity);
non tu as raison, je viens donc de supprimer ce deuxieme else. merci

2022-11-15 11:24 UTC, Planger45 approved these changes

2022-11-15 11:29 UTC, Planger45 approved these changes

2022-11-15 11:40 UTC, DrissB45 approved these changes

2022-11-15 11:57 UTC, sblondeau approved these changes

2022-11-15 11:57 UTC, merged