implementation de la fonction delete activity
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #123
Opened 2022-11-11 18:01 UTC by cedriclv

first commit

2022-11-11 23:12 UTC, Planger45 approved these changes

2022-11-12 11:02 UTC, DrissB45 approved these changes

2022-11-14 10:31 UTC, sblondeau requested changes

2022-11-14 10:31 UTC, sblondeau commented on src/View/Activity/index.html.twig
> +                                            <button>Delete</button>
supprimer

2022-11-14 10:31 UTC, sblondeau commented on src/Controller/ActivityController.php
> +            Header('Location:/activity');
header (minuscule)

2022-11-14 11:03 UTC, cedriclv commented on src/View/Activity/index.html.twig
> +                                            <button>Delete</button>
done

2022-11-14 11:03 UTC, cedriclv commented on src/View/Activity/index.html.twig
>                                          <a href="#">Editer</a>
done

2022-11-14 11:26 UTC, DrissB45 approved these changes

2022-11-14 11:30 UTC, cedriclv commented on src/Controller/ActivityController.php
> +            Header('Location:/activity');
done

2022-11-14 11:44 UTC, merged