make a carousel for species and landscapes
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #124
Opened 2022-11-11 23:55 UTC by Planger45

2022-11-12 11:03 UTC, DrissB45 approved these changes

2022-11-15 15:32 UTC, sblondeau requested changes

2022-11-15 15:32 UTC, sblondeau commented on src/View/Circuits/show.html.twig
> +	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++n
2 fois le meme link

2022-11-15 16:32 UTC, DrissB45 approved these changes

2022-11-16 07:55 UTC, sblondeau approved these changes

2022-11-16 07:55 UTC, merged