S02 us17
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #125
Opened 2022-11-12 12:17 UTC by DrissB45

2022-11-12 14:04 UTC, Planger45 requested changes

2022-11-12 14:04 UTC, Planger45 commented on src/Model/AbstractManager.php
> +        $query = 'SELECT * FROM circuit';
Tu es dans l'abstractManager là ? Change la table dans le bon manager :)

2022-11-12 14:04 UTC, Planger45 commented on src/Controller/CircuitController.php
> +    public function indexCircuitsAdmin(): string
Attention, ici tu supprimes le fait de pouvoir choisir le circuit sur lequel on clique pour aller sur la page DU circuit en question.
C'est une nouvelle method que tu dois créer pour voir les circuits en Admin

2022-11-12 14:04 UTC, Planger45 commented on src/routes.php
> +    'admin/circuits/index' => ['CircuitController', 'indexCircuitsAdmin'],
Tu écrases la precedente route pour les pages unitaires de circuit, il nous la faut :)

2022-11-12 14:05 UTC, DrissB45 commented on src/routes.php
> +    'admin/circuits/index' => ['CircuitController', 'indexCircuitsAdmin'],
Je comptais la mettre dans l'US 18 "Update Circuits"

2022-11-12 14:12 UTC, DrissB45 commented on src/Controller/CircuitController.php
> +    public function indexCircuitsAdmin(): string
pareil, je comptais mettre la méthode show() dans l'US18 de mise à jour des circuits en admin, que j'ai trouvé plus approprié
Cette US 17 s'appelle "lister tous les circuits disponibles"

2022-11-12 14:18 UTC, DrissB45 commented on src/Model/AbstractManager.php
> +        $query = 'SELECT * FROM circuit';
corrigé

2022-11-14 09:46 UTC, Planger45 approved these changes

2022-11-14 11:48 UTC, sblondeau requested changes

2022-11-14 11:48 UTC, sblondeau commented on src/View/Circuits/indexAdmin.html.twig
> +									<div class="btn btn-primary">
non, les classes de type btn se mettent direct sur le lien 
(Éditer avec un accent au passage)
 <a class="btn btn-primary" href="#">Editer</a>

2022-11-14 11:48 UTC, sblondeau commented on src/View/Circuits/indexAdmin.html.twig
> +					<button class="btn btn-secondary mt-3">
Pas de lien dans une balise button !!! c'est soit l'un soit l'autre

2022-11-14 21:49 UTC, Planger45 approved these changes

2022-11-14 22:07 UTC, Planger45 approved these changes

2022-11-14 22:07 UTC, Planger45 commented on src/routes.php
> +    'admin/circuits/index' => ['CircuitController', 'indexCircuitsAdmin'],
Tu efface la route espèces en faisant ça

2022-11-14 23:01 UTC, sblondeau approved these changes

2022-11-14 23:01 UTC, merged