S03 us21 add organism
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #132
Opened 2022-11-14 19:34 UTC by Planger45

2022-11-14 21:28 UTC, DrissB45 approved these changes

2022-11-16 08:36 UTC, sblondeau requested changes

2022-11-16 08:36 UTC, sblondeau commented on src/Controller/OrganismController.php
> +        $urlHeaders = get_headers($organism['picture'], true);
non pas get_headers, c'est éventuellement mime_type_content que tu dois utiliser pour checker le type mime comme j'ai montré en LC

2022-11-16 15:06 UTC, DrissB45 approved these changes

2022-11-16 15:07 UTC, cedriclv approved these changes

2022-11-16 15:48 UTC, merged