S02 us18
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #133
Opened 2022-11-15 09:43 UTC by DrissB45

2022-11-15 11:42 UTC, cedriclv approved these changes

2022-11-15 21:18 UTC, Planger45 requested changes

2022-11-15 21:18 UTC, Planger45 commented on src/View/Circuits/edit.html.twig
> +
Il faudra juste ajouter le block title :)

2022-11-15 21:18 UTC, Planger45 commented on src/View/Circuits/edit.html.twig
> +				{{- circuit.content ?? '' -}}
C'est quoi les "-" dans le block twig?

2022-11-15 21:26 UTC, DrissB45 commented on src/View/Circuits/edit.html.twig
> +				{{- circuit.content ?? '' -}}
C'est pour "trim" le textarea, pour enlever les espaces avant et après le message s'il y en a

2022-11-15 21:31 UTC, DrissB45 commented on src/View/Circuits/edit.html.twig
> +
c'est fait

2022-11-15 22:47 UTC, Planger45 submitted a review, later dismissed

2022-11-16 08:37 UTC, sblondeau approved these changes

2022-11-16 08:38 UTC, merged