add edit orga
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #142
Opened 2022-11-16 16:05 UTC by Planger45

2022-11-16 16:12 UTC, cedriclv submitted a review, later dismissed

2022-11-16 16:33 UTC, sblondeau requested changes

2022-11-16 16:33 UTC, sblondeau commented on src/View/Organism/edit.html.twig
> +					<div class="mb-4 mt-4">
tu ne réutilise pas le meme form entre l'edit et l'ajout ?

2022-11-16 16:39 UTC, Planger45 commented on src/View/Organism/edit.html.twig
> +					<div class="mb-4 mt-4">
Si pourtant c'est exactement le même copier coller....

2022-11-16 17:49 UTC, DrissB45 approved these changes

2022-11-17 08:52 UTC, DrissB45 approved these changes

2022-11-17 09:34 UTC, sblondeau requested changes

2022-11-17 09:34 UTC, sblondeau commented on public/assets/css/header.css
> +    font-size: clamp(*);
c'est quoi clamp(*) ?

2022-11-17 09:51 UTC, Planger45 commented on public/assets/css/header.css
> +    font-size: clamp(*);
Oui j'ai commencé la réflexion hier et j'ai complètement oublié de le retirer

2022-11-17 10:21 UTC, merged