Fix Select Trace : ajout d'un sélecteur pour choisir le tracé du circuit
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #164
Opened 2022-11-19 21:20 UTC by DrissB45

2022-11-20 21:22 UTC, Planger45 approved these changes

2022-11-21 07:55 UTC, sblondeau requested changes

2022-11-21 07:55 UTC, sblondeau commented on src/View/Circuits/circuits-add.html.twig
> +							<option>Jaune</option>
tu devrais faire une constante CIRCUIT_COLORS que tu utiliserait ici pour faire ta boucle, et coté form pour vérifier que la valeur envoyée fait bien partie de ces trois là

2022-11-21 07:55 UTC, sblondeau commented on src/View/Circuits/edit.html.twig
> +				<option>Jaune</option>
tu ne réutilises pas le meme _form inclus pour le add et le edit ?

2022-11-21 13:45 UTC, merged