S04FIX_format_date_evenements
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #168
Opened 2022-11-20 18:46 UTC by cedriclv

2022-11-21 15:19 UTC, Zakari-B submitted a review, later dismissed

2022-11-21 16:18 UTC, Planger45 submitted a review, later dismissed

2022-11-21 20:04 UTC, DrissB45 submitted a review, later dismissed

2022-11-21 21:54 UTC, sblondeau requested changes

2022-11-21 21:54 UTC, sblondeau commented on src/Model/EventManager.php
> +        for ($i = 0; $i < $nbEvents; $i++) {
tu te compliques la vie là... tu devrais récupérer ta date coté Twig, la passer en datetime https://twig.symfony.com/doc/2.x/functions/date.html et la formater à l'affichage via https://twig.symfony.com/doc/2.x/filters/date.html
ça doit fonctionner, mais ton traitement là n'a pas sa place dans le manager à mon sens, c'est vraiment plus de l'affichage

2022-11-22 09:24 UTC, cedriclv commented on src/Model/EventManager.php
> +        for ($i = 0; $i < $nbEvents; $i++) {
Merci, j'ai changé en utilisant twig et plus PHP

2022-11-22 09:34 UTC, Planger45 approved these changes

2022-11-22 09:46 UTC, Zakari-B approved these changes

2022-11-22 09:50 UTC, merged