Gros Fix design admin
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #169
Opened 2022-11-20 19:25 UTC by Planger45

Sylvain je te montre avant de me dire que c'est trop gros comme Fix :P

2022-11-20 20:17 UTC, DrissB45 submitted a review, later dismissed

2022-11-21 09:25 UTC, Zakari-B requested changes

2022-11-21 09:25 UTC, Zakari-B commented on src/View/Circuits/circuits-add.html.twig
> +											<label class="form-label" for="organisms">Espèces visibles sur le circuit</label>
Pas de code commenté

2022-11-21 22:38 UTC, DrissB45 approved these changes

2022-11-22 07:09 UTC, sblondeau requested changes
ta PR ne va pas du tout, beaucoup trop grosse...
je l'ai relu mais tu as 10 commentaires, donc la PR ne va pas passer tout de suite, ce qui va ralentir toutes ces corrections.
Et vu la taille, je suis sans doute passé à coté de plein d'erreurs, donc baisse de qualité globale du code
Tu aurais du faire une PR de fix par section de l'admin, c'était facile là ^^

2022-11-22 07:09 UTC, sblondeau commented on src/Controller/OrganismController.php
> +            header('Location:/admin/especes/index');
pourquoi ajouter index au bout ? admin/especes pour une page qui liste toutes les espèces c'est bien 
ça ne t'empeche pas d'avoir un admin/especes/add ou edit par la suite

2022-11-22 07:09 UTC, sblondeau commented on src/View/Admin/login.html.twig
> +												<br>Administrateur</span>
Connexion en français

2022-11-22 07:09 UTC, sblondeau commented on src/View/Admin/login.html.twig
> +										</div>
Connexion

2022-11-22 07:09 UTC, sblondeau commented on src/View/Circuits/circuits-add.html.twig
> +										</div>
tu gardes cet input finalement ? tu l'affiches qq part ?

2022-11-22 07:09 UTC, sblondeau commented on src/View/Circuits/edit.html.twig
> +									<form action="" method="post" enctype="multipart/form-data">
idem avoir un form include pour add/edit

2022-11-22 07:09 UTC, sblondeau commented on src/View/Circuits/edit.html.twig
> +												<option selected>Gardez la touche Ctrl appuyée pour choisir plusieurs espèces :</option>
ah... tu as fais un select multiple :/ pas fou en terme d'UX, ça ne se fait plus trop, mais bon je ne pense pas que tu aies le temps de refaire ça mieux

2022-11-22 07:09 UTC, sblondeau commented on src/View/Event/edit.html.twig
> +										{% if errors %}
form inclus again

2022-11-22 07:09 UTC, sblondeau commented on src/View/Landscape/add.html.twig
> +									<form action="" method="post" enctype="multipart/form-data">
and again

2022-11-22 07:09 UTC, sblondeau commented on src/View/Organism/add.html.twig
> +									<form action="" method="post" enctype="multipart/form-data">
tjs pareil

2022-11-22 21:46 UTC, closed without merging