Fix resize title nav for mobile
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #172
Opened 2022-11-20 22:08 UTC by Planger45

2022-11-21 09:07 UTC, DrissB45 approved these changes

2022-11-21 09:50 UTC, Zakari-B requested changes

2022-11-21 09:50 UTC, Zakari-B commented on public/assets/css/header.css
> +        font-size: 18px;
Pas de media query pour des tailles de police. Utilisez des clamp ou bootstrap.

2022-11-21 22:37 UTC, DrissB45 approved these changes

2022-11-22 07:48 UTC, sblondeau approved these changes

2022-11-22 09:44 UTC, Zakari-B approved these changes

2022-11-22 09:45 UTC, merged