Fix Form Features : correction de divers problèmes liés aux forms
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #206
Opened 2022-11-22 21:48 UTC by DrissB45

- Remise en place du sélecteur pour le tracé du circuit (il a été mergé mais n'est pas apparu sur dev...)
- Suppression des options génériques par défaut des selects (exemple "choisissez votre question") : pas pratique pour UX

2022-11-22 22:20 UTC, Planger45 submitted a review, later dismissed

2022-11-23 08:19 UTC, Zakari-B approved these changes

2022-11-23 08:21 UTC, Zakari-B requested changes

2022-11-23 08:21 UTC, Zakari-B commented on src/View/Activity/edit.html.twig
> +<h1>Éditer Activité Admin</h1>
Même formulaire pour ton Add et ton Edit, séparer le formulaire dans un autre fichier puis l'include dans les deux pages pour éviter de répéter le code.

2022-11-23 09:35 UTC, Planger45 submitted a review, later dismissed

2022-11-23 10:26 UTC, cedriclv approved these changes

2022-11-23 10:26 UTC, Planger45 approved these changes

2022-11-23 11:01 UTC, Planger45 approved these changes

2022-11-23 11:10 UTC, sblondeau approved these changes

2022-11-23 11:13 UTC, sblondeau approved these changes

2022-11-23 11:13 UTC, merged