S01US02
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #32
Opened 2022-10-26 13:14 UTC by DrissB45

2022-10-26 14:12 UTC, sblondeau requested changes

2022-10-26 14:12 UTC, sblondeau commented on src/View/Include/_footer.html.twig
> +								<h5 class="text-center">
pas de h5 si pas de h4 avant

2022-10-26 14:12 UTC, sblondeau commented on src/View/Include/_footer.html.twig
> +						<div class="text-white text-center mt-3 text-decoration-none">
pour info y a une balise address qui existe en HTML

2022-10-27 07:25 UTC, Planger45 approved these changes

2022-10-27 07:25 UTC, Planger45 commented on public/assets/css/style.css
> +h1 {
Spécifie bien le selecteur du h2 et dans ton fichier correspondant CSS, pas dans le fichier du root.

2022-10-27 07:25 UTC, Planger45 commented on src/View/Home/index.html.twig
> +{# <h1>Hello Wilder !</h1>
Pense à supprimer les commentaires inutiles :)

2022-10-27 21:42 UTC, sblondeau requested changes
image à réduire, beaucoup trop lourdes

2022-10-27 21:42 UTC, sblondeau commented on public/assets/css/footer.css
> +body {
ça n'a pas à etre fait dans ce fichier les retouches sur body

2022-10-27 21:42 UTC, sblondeau commented on src/View/Home/index.html.twig
> +{# <h1>Hello Wilder !</h1>
ce n'est pas fait du coup

2022-10-27 21:42 UTC, sblondeau commented on src/View/Include/_footer.html.twig
> +								<h1 class="text-center">
tu ne dois avoir qu'un seul h1 pour une meme partie (ici ton footer)
et tu n'as pas à mettre des h1 dans des li, utilise css pour styliser ton texte

2022-10-28 08:44 UTC, Planger45 approved these changes

2022-10-28 10:36 UTC, sblondeau requested changes
image à réduire <200ko

2022-10-28 10:48 UTC, cedriclv submitted a review, later dismissed

2022-10-28 11:03 UTC, sblondeau requested changes

2022-10-28 11:03 UTC, sblondeau commented on public/assets/css/footer.css
> +    position: absolute;
à retirer

2022-10-28 11:03 UTC, sblondeau commented on src/View/Include/_footer.html.twig
> +								<button type="button" class="button-footer btn bg-secondary text-white font-weight-bold">Se connecter</button>
ce sont des liens pas des boutons

2022-10-28 11:03 UTC, sblondeau commented on src/View/Include/_footer.html.twig
> +								<button type="button" class="button-footer btn bg-secondary text-white">Mentions légales</button>
idem

2022-10-28 11:11 UTC, cedriclv submitted a review, later dismissed

2022-10-28 11:15 UTC, sblondeau approved these changes

2022-10-28 11:15 UTC, merged