S01 us01 activity page creation
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #34
Opened 2022-10-26 20:56 UTC by cedriclv

Please can you review this pull request about the activity page (creation of html, style, sql).

Thanks
Cédric

2022-10-27 07:46 UTC, Planger45 reviewed
C'est pas le bon US cédric par contre => US#6

2022-10-27 07:46 UTC, Planger45 commented on src/View/Activity/activity.html.twig
> +	{# fake navbar TO REMOVE  area#}
A retirer la fake navbar :)

2022-10-27 07:46 UTC, Planger45 commented on src/routing.php
> +//var_dump($controller);
Pense à supprimer les commentaires inutiles :)

2022-10-27 09:25 UTC, sblondeau requested changes
ta user story c'est faire une page listant les activités
donc je ne veux pas d'event ici
je ne veux pas d'update/insert etc
tu fais trop de chose

2022-10-27 09:25 UTC, sblondeau commented on public/assets/css/activity.css
> +        background-image: url("https://img.freepik.com/photos-gratuite/route-etroite-dans-champ-herbeux-vert-entoure-arbres-verts-soleil-eclatant-arriere-plan_181624-9968.jpg?w=2000");
tes images ne doivent pas venir d'un site externe

2022-10-27 09:25 UTC, sblondeau commented on public/assets/css/activity.css
> +@media screen and (max-width:400px) {
pas certain que la media query soit nécessaire

2022-10-27 09:25 UTC, sblondeau commented on src/Model/EventManager.php
> +        $query = 'SELECT title,cost,description,
euh... non

2022-10-27 10:27 UTC, Planger45 approved these changes

2022-10-28 08:37 UTC, Planger45 approved these changes

2022-10-28 08:47 UTC, DrissB45 reviewed
Code : OK pour moi
Attention : redimensionner image à moins de 200ko

2022-10-28 08:54 UTC, cedriclv commented
Correction requested by Driss has just been made on the last commit

2022-10-28 09:01 UTC, DrissB45 submitted a review, later dismissed
OK !

2022-10-28 10:27 UTC, merged