S01 US07 evenements mis à jour dans cette request (sans les activités…
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #44
Opened 2022-10-27 14:10 UTC by cedriclv

… comme precedemment)

2022-10-27 14:53 UTC, Planger45 submitted a review, later dismissed

2022-10-27 14:59 UTC, sblondeau requested changes

2022-10-27 14:59 UTC, sblondeau commented on src/Model/EventManager.php
> +    public function insert(array $item): int
insert() et update() à virer

2022-10-27 14:59 UTC, sblondeau commented on src/View/Activity/activity.html.twig
> +				<img class="rounded-top" src="https://img.freepik.com/photos-gratuite/route-etroite-dans-champ-herbeux-vert-entoure-arbres-verts-soleil-eclatant-arriere-plan_181624-9968.jpg?w=2000" class="card-i
image :p

2022-10-28 09:42 UTC, Planger45 approved these changes

2022-10-28 09:53 UTC, Zakari-B approved these changes

2022-10-28 09:56 UTC, merged