Navbar
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #46
Opened 2022-10-27 14:19 UTC by stephaparicio

pull request de ma navbar

2022-10-27 15:10 UTC, Planger45 commented on src/View/Home/_navbar.html.twig
> +            <a class="nav-link text-secondary" href="#">Contatc</a>
Une faute sur "Contact"

2022-10-27 15:10 UTC, Planger45 commented on src/View/Home/_navbar.html.twig
> +
Tu as oublié de mettre un titre h1

2022-10-27 21:39 UTC, sblondeau requested changes
remarque à corriger avant de passer la PR en "Reviewed"

2022-10-28 10:25 UTC, Planger45 approved these changes

2022-10-28 10:37 UTC, sblondeau approved these changes

2022-10-28 10:37 UTC, merged