S02 us14
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #79
Opened 2022-10-29 21:33 UTC by Planger45

Add Form twig and responsive form

2022-10-29 21:36 UTC, Planger45 commented on src/Controller/FormController.php
> +     * Display home page
form page

2022-10-29 21:44 UTC, Planger45 commented on src/Controller/FormController.php
> +     * Display home page
It's Ok next commit with secure form

2022-10-31 12:09 UTC, DrissB45 reviewed
Rien à dire au niveau du code

J'ai fait des petits commentaires au niveau de l'orthographe et de la cohérence de syntaxe entre les phrases d'erreurs mais rien de super important

2022-10-31 12:09 UTC, DrissB45 commented on src/Controller/FormController.php
> +            if (strlen($addSub['lastname']) > self::LASTNAME_LENGTH) {
enlever "est trop long" pour garder une cohérence avec les autres phrases d'erreur

2022-10-31 12:09 UTC, DrissB45 commented on src/Controller/FormController.php
> +            if (!filter_var(($addSub['email']), FILTER_VALIDATE_EMAIL)) {
"e-mail"

2022-10-31 12:09 UTC, DrissB45 commented on src/Controller/FormController.php
> +        if (empty($addSub['email'])) {
"e-mail"

2022-10-31 12:09 UTC, DrissB45 commented on src/View/Contact/form.html.twig
> +						<label class="form-label" for="email">Adresse E-mail:</label>
e-mail

2022-10-31 12:09 UTC, DrissB45 commented on src/View/Contact/form.html.twig
> +							<option selected>Choisissez votre Question?</option>
J'aurais plus mis "Choisissez votre question :" -> pas de majuscule à Question et pas de point d'interrogation à la fin (cette phrase n'est pas une question en soi)

2022-10-31 23:25 UTC, Planger45 commented on src/Controller/FormController.php
> +            if (strlen($addSub['lastname']) > self::LASTNAME_LENGTH) {
Merci je l'avais modifié dans ce sens mais visiblement ça n'a pas bougé :)

2022-11-02 22:09 UTC, DrissB45 approved these changes

2022-11-03 07:43 UTC, sblondeau requested changes

2022-11-03 07:43 UTC, sblondeau commented on src/Controller/FormController.php
> +                $errors[] = 'Le nom doit être inférieur à ' . self::LASTNAME_LENGTH . 'caractères !';
il manque une espace devant caractère

2022-11-03 07:43 UTC, sblondeau commented on src/Controller/FormController.php
> +                $errors[] = 'Le prénom doit être inférieur à ' . self::FIRSTNAME_LENGTH . 'caractères !';
idem

2022-11-03 07:43 UTC, sblondeau commented on src/Controller/FormController.php
> +class FormController extends AbstractController
à renommer, FormController c'est pas parlant ! ContactController maybe ?

2022-11-03 07:43 UTC, sblondeau commented on src/Controller/FormController.php
> +            $addSub = array_map('trim', $_POST);
c'est quoi $addSub ?  pas parlant

2022-11-03 07:43 UTC, sblondeau commented on src/View/Contact/form.html.twig
> +							<option selected>Choisissez votre Question?</option>
+1

2022-11-03 11:14 UTC, DrissB45 approved these changes

2022-11-03 11:24 UTC, DrissB45 approved these changes

2022-11-03 11:41 UTC, sblondeau approved these changes

2022-11-03 11:41 UTC, merged