change of the activity side to alternate the image and text
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #87
Opened 2022-11-01 13:23 UTC by cedriclv

2022-11-01 14:48 UTC, Planger45 submitted a review, later dismissed
Je te fais confiance je vois pas le résultat 👍

2022-11-02 07:57 UTC, sblondeau requested changes

2022-11-02 07:57 UTC, sblondeau commented on src/View/Activity/activity.html.twig
> +		{% if counter%2 != 0 %}
non pas la peine de setter un counter à 0 ue tu incrémentes
tu as acces au tour de boucle en cours via {{ loop.index0 }} et tu peux faire un {% if loop.index0 is even }}

2022-11-02 07:57 UTC, sblondeau commented on src/View/Activity/activity.html.twig
> +		{% if counter%2 != 0 %}
au delà de ça, tu te répète beaucoup là, tu dois faire en sorte de ne pas répéter tout le bloc de code pour pair ou impair.
si tu dois juste décaler le bloc texte et le bloc image, plutot qu'en twig, fait ça en css avec un nth-chid(even) et la propriété order de flex

2022-11-02 07:57 UTC, sblondeau commented on src/View/Activity/activity.html.twig
> +					<img class="eventsImg rounded" src="/assets/images/imgPlaceHolder.jpg" alt="eventPicture" srcset="">
tu pourrais le faire un une ligne avec qq chose comme
`<img class="eventsImg rounded" src="{{ event.picture_link is null ? '/assets/images/imgPlaceHolder.jpg' : event.picture_link  }}" alt="photo de l'événement">`

2022-11-02 07:57 UTC, sblondeau commented on src/View/Activity/activity.html.twig
> +	{% set counter = counter + 1 %}
à retirer

2022-11-02 09:33 UTC, cedriclv commented
update d to follow recommandations (css and if shortcuts)

2022-11-02 09:40 UTC, Zakari-B requested changes

2022-11-02 09:40 UTC, Zakari-B commented on src/View/Activity/activity.html.twig
> +					<h2 class="text-center m-5 essai">{{ activity.title}}</h2>
essai ?

2022-11-02 22:07 UTC, DrissB45 approved these changes

2022-11-07 07:54 UTC, sblondeau requested changes
le dossier upload ne doit pas etre versionné, là tu as envoyé plein d'images de test sur github, supprime les et ajoute ton .gitignore comme on a dit verndredi

2022-11-07 14:50 UTC, DrissB45 submitted a review, later dismissed

2022-11-07 16:37 UTC, sblondeau approved these changes

2022-11-07 19:55 UTC, DrissB45 approved these changes

2022-11-07 22:19 UTC, sblondeau approved these changes

2022-11-07 22:19 UTC, merged