S02 us25 creer activité
WildCodeSchool/2022-09-php-orleans-project-gatinaisnature pull request #99
Opened 2022-11-04 15:21 UTC by cedriclv

2022-11-04 15:57 UTC, Planger45 submitted a review, later dismissed

2022-11-04 16:14 UTC, DrissB45 approved these changes

2022-11-04 16:34 UTC, sblondeau requested changes

2022-11-04 16:34 UTC, sblondeau commented on src/Controller/ActivityController.php
> +        if (!isset($inputs['description']) || strlen($inputs['description']) > 200) {
variable ou constante pour la longueur max

2022-11-04 16:34 UTC, sblondeau commented on src/Controller/ActivityController.php
> +    public function getFormErrors(array $inputs, array $errors): array
$activity plutot que $inputs

2022-11-04 16:34 UTC, sblondeau commented on src/Controller/ActivityController.php
> +            $inputs = array_map('trim', $_POST);
$activity

2022-11-04 16:34 UTC, sblondeau commented on src/Controller/ActivityController.php
> +                $errors[] = 'L\'image doit etre de type jpg ou png';
fais qq chose comme ça c'est meiux
$errors[] = 'L\'image doit avoir une des ces extensions : ' .  implode(',', $allowedExtensions);

2022-11-04 16:34 UTC, sblondeau commented on src/Controller/ActivityController.php
> +            if ($_FILES['picture']['size'] > 200000) {
idem ici mets fait un $maxSize=200000 que tu réutilise dans le if ET dans le message d'erreur
'L'image doit etre d\'une taille maximum de '. $maxSize / 100000 . ' Mo'

2022-11-04 16:34 UTC, sblondeau commented on src/Controller/ActivityController.php
> +            //taille/extension/mettre un unique id pour ne pas ecraser les images.
enlève tes commentaires inutiles

2022-11-06 12:26 UTC, DrissB45 approved these changes

2022-11-07 08:40 UTC, merged